package it.course.myrecipesc4.entity;
// Generated 2 mar 2021, 16:59:05 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chef generated by hbm2java
 */
@Entity
@Table(name = "chef", catalog = "myrecipesc4")
public class Chef implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long chefId;
	private String chefName;
	private String chefLastName;
	private String biography;
	private byte[] image;
	private Set<Recipe> recipes = new HashSet<Recipe>(0);

	public Chef() {
	}

	public Chef(long chefId, String chefName, String chefLastName, String biography, byte[] image) {
		this.chefId = chefId;
		this.chefName = chefName;
		this.chefLastName = chefLastName;
		this.biography = biography;
		this.image = image;
	}

	public Chef(long chefId, String chefName, String chefLastName, String biography, byte[] image,
			Set<Recipe> recipes) {
		this.chefId = chefId;
		this.chefName = chefName;
		this.chefLastName = chefLastName;
		this.biography = biography;
		this.image = image;
		this.recipes = recipes;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "chef_id", unique = true, nullable = false)
	public long getChefId() {
		return this.chefId;
	}

	public void setChefId(long chefId) {
		this.chefId = chefId;
	}

	@Column(name = "chef_name", nullable = false, length = 45)
	public String getChefName() {
		return this.chefName;
	}

	public void setChefName(String chefName) {
		this.chefName = chefName;
	}

	@Column(name = "chef_last_name", nullable = false, length = 45)
	public String getChefLastName() {
		return this.chefLastName;
	}

	public void setChefLastName(String chefLastName) {
		this.chefLastName = chefLastName;
	}

	@Column(name = "biography", nullable = false, columnDefinition="TEXT")
	public String getBiography() {
		return this.biography;
	}

	public void setBiography(String biography) {
		this.biography = biography;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chef")
	public Set<Recipe> getRecipes() {
		return this.recipes;
	}

	public void setRecipes(Set<Recipe> recipes) {
		this.recipes = recipes;
	}

}
