package it.course.myrecipesc4.entity;
// Generated 2 mar 2021, 16:59:05 by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "myrecipesc4")
public class Comment implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long commentId;
	private Recipe recipe;
	private User user;
	private String content;
	private String response;
	private boolean approved;
	private Date commentDate;
	private Date responseDate;

	public Comment() {
	}

	public Comment(long commentId, Recipe recipe, User user, String content, boolean approved, Date commentDate) {
		this.commentId = commentId;
		this.recipe = recipe;
		this.user = user;
		this.content = content;
		this.approved = approved;
		this.commentDate = commentDate;
	}

	public Comment(long commentId, Recipe recipe, User user, String content, String response, boolean approved,
			Date commentDate, Date responseDate) {
		this.commentId = commentId;
		this.recipe = recipe;
		this.user = user;
		this.content = content;
		this.response = response;
		this.approved = approved;
		this.commentDate = commentDate;
		this.responseDate = responseDate;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "comment_id", unique = true, nullable = false)
	public long getCommentId() {
		return this.commentId;
	}

	public void setCommentId(long commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_id", nullable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "response")
	public String getResponse() {
		return this.response;
	}

	public void setResponse(String response) {
		this.response = response;
	}

	@Column(name = "approved", nullable = false)
	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "comment_date", nullable = false, length = 19)
	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "response_date", length = 19)
	public Date getResponseDate() {
		return this.responseDate;
	}

	public void setResponseDate(Date responseDate) {
		this.responseDate = responseDate;
	}

}
