package it.course.myrecipesc4.entity;
// Generated 2 mar 2021, 16:59:05 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ingredient generated by hbm2java
 */
@Entity
@Table(name = "ingredient", catalog = "myrecipesc4", uniqueConstraints = @UniqueConstraint(columnNames = "ingredient_name"))
public class Ingredient implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long ingredientId;
	private String ingredientName;
	private String ingredientDescription;
	private Set<RecipeHasIngredient> recipeHasIngredients = new HashSet<RecipeHasIngredient>(0);

	public Ingredient() {
	}

	public Ingredient(long ingredientId, String ingredientName) {
		this.ingredientId = ingredientId;
		this.ingredientName = ingredientName;
	}

	public Ingredient(long ingredientId, String ingredientName, String ingredientDescription,
			Set<RecipeHasIngredient> recipeHasIngredients) {
		this.ingredientId = ingredientId;
		this.ingredientName = ingredientName;
		this.ingredientDescription = ingredientDescription;
		this.recipeHasIngredients = recipeHasIngredients;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ingredient_id", unique = true, nullable = false)
	public long getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(long ingredientId) {
		this.ingredientId = ingredientId;
	}

	@Column(name = "ingredient_name", nullable = false, length = 45)
	public String getIngredientName() {
		return this.ingredientName;
	}

	public void setIngredientName(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	@Column(name = "ingredient_description", length = 45)
	public String getIngredientDescription() {
		return this.ingredientDescription;
	}

	public void setIngredientDescription(String ingredientDescription) {
		this.ingredientDescription = ingredientDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingredient")
	public Set<RecipeHasIngredient> getRecipeHasIngredients() {
		return this.recipeHasIngredients;
	}

	public void setRecipeHasIngredients(Set<RecipeHasIngredient> recipeHasIngredients) {
		this.recipeHasIngredients = recipeHasIngredients;
	}

}
