package it.course.myrecipesc4.entity;
// Generated 2 mar 2021, 16:59:05 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RatingId generated by hbm2java
 */
@Embeddable
public class RatingId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long recipeId;
	private long userId;

	public RatingId() {
	}

	public RatingId(long recipeId, long userId) {
		this.recipeId = recipeId;
		this.userId = userId;
	}

	@Column(name = "recipe_id", nullable = false)
	public long getRecipeId() {
		return this.recipeId;
	}

	public void setRecipeId(long recipeId) {
		this.recipeId = recipeId;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RatingId))
			return false;
		RatingId castOther = (RatingId) other;

		return (this.getRecipeId() == castOther.getRecipeId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRecipeId();
		result = 37 * result + (int) this.getUserId();
		return result;
	}

}
