package it.course.myrecipesc4.entity;
// Generated 2 mar 2021, 16:59:05 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name = "rating", catalog = "myrecipesc4")
public class Rating implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private RatingId id;
	private Recipe recipe;
	private User user;
	private short rate;

	public Rating() {
	}

	public Rating(RatingId id, Recipe recipe, User user, short rate) {
		this.id = id;
		this.recipe = recipe;
		this.user = user;
		this.rate = rate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "recipeId", column = @Column(name = "recipe_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public RatingId getId() {
		return this.id;
	}

	public void setId(RatingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_id", nullable = false, insertable = false, updatable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "rate", nullable = false)
	public short getRate() {
		return this.rate;
	}

	public void setRate(short rate) {
		this.rate = rate;
	}

}
