package it.course.myrecipesc4.entity;
// Generated 2 mar 2021, 16:59:05 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecipeHasIngredient generated by hbm2java
 */
@Entity
@Table(name = "recipe_has_ingredient", catalog = "myrecipesc4")
public class RecipeHasIngredient implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private RecipeHasIngredientId id;
	private Ingredient ingredient;
	private Recipe recipe;
	private String quantity;

	public RecipeHasIngredient() {
	}

	public RecipeHasIngredient(RecipeHasIngredientId id, Ingredient ingredient, Recipe recipe) {
		this.id = id;
		this.ingredient = ingredient;
		this.recipe = recipe;
	}

	public RecipeHasIngredient(RecipeHasIngredientId id, Ingredient ingredient, Recipe recipe, String quantity) {
		this.id = id;
		this.ingredient = ingredient;
		this.recipe = recipe;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "recipeRecipeId", column = @Column(name = "recipe_recipe_id", nullable = false)),
			@AttributeOverride(name = "ingredientIngredientId", column = @Column(name = "ingredient_ingredient_id", nullable = false)) })
	public RecipeHasIngredientId getId() {
		return this.id;
	}

	public void setId(RecipeHasIngredientId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ingredient_ingredient_id", nullable = false, insertable = false, updatable = false)
	public Ingredient getIngredient() {
		return this.ingredient;
	}

	public void setIngredient(Ingredient ingredient) {
		this.ingredient = ingredient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_recipe_id", nullable = false, insertable = false, updatable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@Column(name = "quantity", length = 20)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

}
