package it.course.myrecipesc4.entity;
// Generated 2 mar 2021, 16:59:05 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecipeHasIngredientId generated by hbm2java
 */
@Embeddable
public class RecipeHasIngredientId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long recipeRecipeId;
	private long ingredientIngredientId;

	public RecipeHasIngredientId() {
	}

	public RecipeHasIngredientId(long recipeRecipeId, long ingredientIngredientId) {
		this.recipeRecipeId = recipeRecipeId;
		this.ingredientIngredientId = ingredientIngredientId;
	}

	@Column(name = "recipe_recipe_id", nullable = false)
	public long getRecipeRecipeId() {
		return this.recipeRecipeId;
	}

	public void setRecipeRecipeId(long recipeRecipeId) {
		this.recipeRecipeId = recipeRecipeId;
	}

	@Column(name = "ingredient_ingredient_id", nullable = false)
	public long getIngredientIngredientId() {
		return this.ingredientIngredientId;
	}

	public void setIngredientIngredientId(long ingredientIngredientId) {
		this.ingredientIngredientId = ingredientIngredientId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecipeHasIngredientId))
			return false;
		RecipeHasIngredientId castOther = (RecipeHasIngredientId) other;

		return (this.getRecipeRecipeId() == castOther.getRecipeRecipeId())
				&& (this.getIngredientIngredientId() == castOther.getIngredientIngredientId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRecipeRecipeId();
		result = 37 * result + (int) this.getIngredientIngredientId();
		return result;
	}

}
