package it.course.myrecipesc4.entity;
// Generated 2 mar 2021, 16:59:05 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRecipeImage generated by hbm2java
 */
@Entity
@Table(name = "user_recipe_image", catalog = "myrecipesc4")
public class UserRecipeImage implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private UserRecipeImageId id;
	private Recipe recipe;
	private User user;
	private String comment;
	private boolean approved;
	private byte[] image;

	public UserRecipeImage() {
	}

	public UserRecipeImage(UserRecipeImageId id, Recipe recipe, User user, String comment, boolean approved,
			byte[] image) {
		this.id = id;
		this.recipe = recipe;
		this.user = user;
		this.comment = comment;
		this.approved = approved;
		this.image = image;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "recipeId", column = @Column(name = "recipe_id", nullable = false)) })
	public UserRecipeImageId getId() {
		return this.id;
	}

	public void setId(UserRecipeImageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_id", nullable = false, insertable = false, updatable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "comment", nullable = false)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "approved", nullable = false)
	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
